"""
Weather Edge Analyzer — License System
=======================================
Access codes are generated by you (the seller) and given to paying subscribers.
Each code encodes: expiry date + unique subscriber ID.
No internet needed to validate — pure local crypto.

HOW IT WORKS:
  1. You run: python generate_code.py --days 30 --id SUB001
  2. You send the code to the buyer via DM
  3. Buyer enters it once on first launch — stored locally
  4. Every launch checks: code valid? not expired? show the app
  5. Each month you send a new code after they pay

TAMPER PROOF:
  Codes are HMAC-SHA256 signed with your secret key.
  Changing the expiry date in the stored file invalidates it.
  The secret key never leaves your machine.
"""

import hmac, hashlib, json, os, sys, re, base64, time
from datetime import datetime, timedelta, timezone
from pathlib import Path

# Fix Windows console encoding for Unicode characters
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass


# ─────────────────────────────────────────────────────────────────────────────
# SECRET KEY — loaded from environment variable WEATHER_SECRET_KEY.
# Set this in Render dashboard → Environment → Add Environment Variable.
# Never hardcode this in the repo.
# To generate a new key: python -c "import secrets; print(secrets.token_hex(32))"
# ─────────────────────────────────────────────────────────────────────────────
SECRET_KEY = os.environ.get(
    "WEATHER_SECRET_KEY",
    "80a9936885d0e1e994d11e8ab38b3b82d6dd17632659c3942ad98234efe75111"  # fallback for local dev only
)

# Where license is stored on user's machine
LICENSE_FILE = Path.home() / ".weather_edge_license"

# App version — bump this when you release updates
APP_VERSION  = "1.1.0"
UPDATE_NOTES = "Initial release"


def _sign(payload: str) -> str:
    """HMAC-SHA256 signature of payload using SECRET_KEY."""
    return hmac.new(
        SECRET_KEY.encode(),
        payload.encode(),
        hashlib.sha256
    ).hexdigest()


def generate_code(subscriber_id: str, days_valid: int) -> str:
    """
    Generate an access code for a subscriber.
    Run this on YOUR machine, never distribute this function.

    Format: base64( JSON({id, exp, ver}) ) + "." + HMAC_signature
    """
    exp_ts = int(time.time()) + (days_valid * 86400)
    payload = json.dumps({
        "id":  subscriber_id,
        "exp": exp_ts,
        "ver": APP_VERSION,
    }, separators=(',', ':'))

    b64 = base64.urlsafe_b64encode(payload.encode()).decode()
    sig  = _sign(b64)
    return f"{b64}.{sig[:16]}"   # 16-char sig suffix keeps codes short-ish


def validate_code(code: str) -> dict:
    """
    Validate an access code. Returns dict with:
      { ok: bool, error: str|None, subscriber_id: str|None,
        expires_at: datetime|None, days_left: int|None }
    """
    try:
        if "." not in code:
            return {"ok": False, "error": "Invalid code format"}

        b64, sig_given = code.rsplit(".", 1)

        # Verify signature
        sig_expected = _sign(b64)[:16]
        if not hmac.compare_digest(sig_given.lower(), sig_expected.lower()):
            return {"ok": False, "error": "Invalid code — signature mismatch"}

        # Decode payload
        payload = json.loads(base64.urlsafe_b64decode(b64 + "==").decode())
        exp_ts  = payload.get("exp", 0)
        sub_id  = payload.get("id", "unknown")
        now_ts  = int(time.time())

        if now_ts > exp_ts:
            exp_dt    = datetime.fromtimestamp(exp_ts)
            days_ago  = (now_ts - exp_ts) // 86400
            return {
                "ok":    False,
                "error": f"Code expired {days_ago} day(s) ago ({exp_dt.strftime('%b %d %Y')}). "
                         f"DM @NethulaRashvin to renew.",
                "subscriber_id": sub_id,
                "expires_at":    exp_dt,
                "days_left":     0,
            }

        days_left  = max(0, (exp_ts - now_ts) // 86400)
        expires_at = datetime.fromtimestamp(exp_ts)
        return {
            "ok":            True,
            "error":         None,
            "subscriber_id": sub_id,
            "expires_at":    expires_at,
            "days_left":     days_left,
        }

    except Exception as e:
        return {"ok": False, "error": f"Code validation error: {e}"}


def save_license(code: str) -> None:
    """Save validated code to local license file."""
    data = {"code": code, "saved_at": int(time.time())}
    LICENSE_FILE.write_text(json.dumps(data))


def load_license() -> str | None:
    """Load saved license code from disk. Returns None if not found."""
    try:
        if LICENSE_FILE.exists():
            data = json.loads(LICENSE_FILE.read_text())
            return data.get("code")
    except Exception:
        pass
    return None


def clear_license() -> None:
    """Remove stored license (for re-entry)."""
    try:
        LICENSE_FILE.unlink()
    except Exception:
        pass


def check_license_or_prompt() -> dict:
    """
    Main entry point called at app startup.
    Returns validated license info if access granted, exits if not.
    """
    print("\n" + "─" * 56)
    print("  ⚡ Weather Edge Analyzer")
    print(f"  Version {APP_VERSION}")
    print("─" * 56)

    # Try saved license first
    saved = load_license()
    if saved:
        result = validate_code(saved)
        if result["ok"]:
            print(f"  ✓ Access granted  ·  {result['days_left']} days remaining")
            print(f"  Subscriber: {result['subscriber_id']}")
            print(f"  Expires: {result['expires_at'].strftime('%b %d, %Y')}")
            print("─" * 56 + "\n")
            return result
        else:
            # Saved code expired or invalid — clear it and ask for new one
            clear_license()
            print(f"\n  ⚠  {result['error']}\n")

    # Prompt for access code
    print("  Enter your access code to continue.")
    print("  No code? DM @NethulaRashvin on X.\n")

    attempts = 0
    while attempts < 3:
        code = input("  Access code: ").strip()
        if not code:
            attempts += 1
            continue

        result = validate_code(code)
        if result["ok"]:
            save_license(code)
            print(f"\n  ✓ Access granted! Welcome, {result['subscriber_id']}")
            print(f"  Valid for {result['days_left']} more days.")
            print("─" * 56 + "\n")
            return result
        else:
            attempts += 1
            print(f"\n  ✗ {result['error']}")
            if attempts < 3:
                print(f"  {3 - attempts} attempt(s) remaining.\n")

    print("\n  Access denied. DM @NethulaRashvin on X for a valid code.")
    print("─" * 56)
    sys.exit(1)
